version: '3'
services:
  # app:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/var/www/html
  #   ports:
  #     - "8000:8000"
  fastapi:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8001" 